// Andhra Pradesh & Telangana Locations Data
const LOCATIONS_DATA = {
  "Guntur": {
    "Tenali": ["Angalakuduru", "Nandivelugu", "Burripalem", "Chinaravuru", "Kolakaluru"],
    "Mangalagiri": ["Atmakuru", "Nowluru", "Nidamarru", "Pedavadlapudi", "Kaza"],
    "Bapatla": ["Karlapalem", "Appikatla", "Murukondapadu", "Jammulapalem", "Pittalavanipalem"],
    "Narasaraopet": ["Jonnalagadda", "Kesavanayanipalem", "Ravipadu", "Petlurivaripalem", "Rompicherla"],
    "Sattenapalle": ["Dhulipalla", "Garrpadu", "Kankanalapalle", "Pedamakkena", "Abburu"]
  },
  "Krishna": {
    "Gannavaram": ["Mustabad", "Savalyapuram", "Kesarapalle", "Veerapanenigudem", "Purushothapatnam"],
    "Gudivada": ["Chilakalapudi", "Billapadu", "Valivarthipadu", "Mallayapalem", "Mandavalli"],
    "Machilipatnam": ["Pothepalli", "Chilakalapudi", "Arisepalli", "Karaivaripalem", "Tarakaturu"],
    "Nuzvid": ["Borragudem", "Hanuman Junction", "Musaligunta", "Tukkuluru", "Venkatayapalem"]
  },
  "West Godavari": {
    "Bhimavaram": ["Losarigutlapadu", "Gollalakoderu", "Dharmavaram", "Rayalam", "Pedagaram"],
    "Tadepalligudem": ["Kunchanapalli", "Pattigadda", "Kondruprolu", "Madhavaram", "Jagannadhapuram"],
    "Tanuku": ["Velpuru", "Duvva", "Tetali", "Kommareddypalle", "Mandapaka"],
    "Palakollu": ["Goraganamudi", "Chinnagaruvu", "Lankalakoderu", "Sivadevuni Chikkala"]
  },
  "East Godavari": {
    "Rajahmundry Rural": ["Torredu", "Kateru", "Hukumpeta", "Bommur", "Dowleswaram"],
    "Kakinada Rural": ["Thimmapuram", "Sarpavaram", "Kovvada", "Ganganapalle", "Cheediga"],
    "Amalapuram": ["Bhatnavilli", "Bandarulanka", "Peruru", "Indupalle", "Sampara"]
  },
  "Kurnool": {
    "Adoni": ["Arekal", "Mandagiri", "Basarakodu", "Chinnathumbalam", "Peddathumbalam"],
    "Nandyal": ["Panyam", "Mahanandi", "Gajulapalle", "Bandi Atmakur", "Ayyalur"],
    "Yemmiganur": ["Banavasi", "Gudikal", "Mugathi", "Kadivella", "Soganuru"]
  },
  "Warangal": {
    "Hanamkonda": ["Bhimaram", "Palakurthy", "Madikonda", "Gopalapuram", "Kazipet"],
    "Narsampet": ["Chennaraopet", "Duggondi", "Khanapur", "Nekkonda", "Maheswaram"],
    "Parkal": ["Nagaram", "Regonda", "Shyampet", "Mogullapalle", "Chityal"]
  },
  "Khammam": {
    "Khammam Rural": ["Arempula", "Mallemadugu", "Edulapuram", "Gudimalla", "Polepalli"],
    "Madhira": ["Dendukuru", "Siripuram", "Khammampadu", "Illuru", "Atkur"],
    "Sathupalli": ["Gangaram", "Kakarlapalli", "Rejerla", "Bethupalli", "Kistaram"]
  }
};

// Initial Labourers Dataset
const INITIAL_WORKERS = [
  {
    id: "w1",
    name_en: "Rambabu & Team (Jai Kisan Gang)",
    name_te: "రాంబాబు & బృందం (జై కిసాన్ ముఠా)",
    type: "group", // group or individual
    groupSize: 14,
    district: "Guntur",
    mandal: "Tenali",
    village: "Burripalem",
    skills: ["harvesting", "planting", "loading"],
    skills_labels_en: ["Paddy Harvesting", "Paddy Transplantation", "Grain Loading"],
    skills_labels_te: ["వరి కోత", "వరి నాట్లు", "ధాన్యం మోత & రవాణా"],
    dailyWage: 650,
    experience: "12 Years",
    rating: 4.9,
    reviewsCount: 38,
    status: "available", // available, busy, booked
    phone: "+91 98480 12345",
    whatsapp: "919848012345",
    avatar: "https://images.unsplash.com/photo-1595278069441-2cf29f8005a4?auto=format&fit=crop&w=200&q=80",
    verified: true,
    availableDates: ["2026-09-19", "2026-09-20", "2026-09-21", "2026-09-24"],
    equipment: ["Sickles (కొడవళ్లు)", "Paddy Thresher Support", "Tarp Covers"],
    bio_en: "Fast and reliable 14-member experienced harvester group with complete sickle tools. 5 acres harvested per day.",
    bio_te: "14 మంది సభ్యుల అనుభవజ్ఞులైన వరి కోత బృందం. రోజుకు 5 ఎకరాలు కోత చేయగల నైపుణ్యం."
  },
  {
    id: "w2",
    name_en: "Venkatappa (Certified Sprayer)",
    name_te: "వెంకటప్ప (స్ప్రేయింగ్ స్పెషలిస్ట్)",
    type: "individual",
    groupSize: 1,
    district: "Guntur",
    mandal: "Mangalagiri",
    village: "Nowluru",
    skills: ["spraying", "tractor"],
    skills_labels_en: ["Pesticide Spraying", "Tractor Driving"],
    skills_labels_te: ["మందుల పిచికారీ", "ట్రాక్టర్ నడపడం"],
    dailyWage: 800,
    experience: "9 Years",
    rating: 4.8,
    reviewsCount: 29,
    status: "available",
    phone: "+91 94401 56789",
    whatsapp: "919440156789",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",
    verified: true,
    availableDates: ["2026-09-19", "2026-09-21", "2026-09-22"],
    equipment: ["Own Motorised Stihl Sprayer", "Battery Sprayer", "Safety Mask & Goggles"],
    bio_en: "Expert in Chilli & Cotton pesticide spraying using high-pressure power sprayers. Certified in safe agro-chemical dosage.",
    bio_te: "మిర్చి మరియు పత్తికి సొంత పవర్ స్ప్రేయర్‌తో పురుగు మందులు, ఎరువులు జాగ్రత్తగా పిచికారీ చేయడంలో నిపుణుడు."
  },
  {
    id: "w3",
    name_en: "Lakshmi Devi & Mahila Sangham",
    name_te: "లక్ష్మీదేవి & మహిళా సంఘం",
    type: "group",
    groupSize: 10,
    district: "Krishna",
    mandal: "Gudivada",
    village: "Valivarthipadu",
    skills: ["weeding", "plucking", "planting"],
    skills_labels_en: ["Weeding (కలుపు తీత)", "Chilli/Cotton Plucking", "Transplantation"],
    skills_labels_te: ["కలుపు తీత", "మిర్చి/పత్తి ఏరడం", "వరి నాట్లు"],
    dailyWage: 500,
    experience: "15 Years",
    rating: 5.0,
    reviewsCount: 45,
    status: "available",
    phone: "+91 98492 88990",
    whatsapp: "919849288990",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80",
    verified: true,
    availableDates: ["2026-09-19", "2026-09-20", "2026-09-22", "2026-09-23"],
    equipment: ["Weeding Trowels (తొవ్వెడం పనిముట్లు)", "Picking Bags"],
    bio_en: "Highly disciplined 10-women group specialized in thorough weeding and clean cotton & chilli picking.",
    bio_te: "10 మంది మహిళా కూలీల బృందం. పొలంలో కలుపు తీత, మిర్చి మరియు పత్తి ఎలాంటి నష్టం లేకుండా నాణ్యంగా ఏరుతారు."
  },
  {
    id: "w4",
    name_en: "Srinivas Rao (Pro Tractor Operator)",
    name_te: "శ్రీనివాసరావు (ట్రాక్టర్ & రోటవేటర్ డ్రైవర్)",
    type: "individual",
    groupSize: 1,
    district: "West Godavari",
    mandal: "Bhimavaram",
    village: "Rayalam",
    skills: ["tractor", "loading"],
    skills_labels_en: ["Tractor Ploughing", "Rotavator Operation", "Paddy Transport"],
    skills_labels_te: ["ట్రాక్టర్ దుక్కి దున్నడం", "రోటవేటర్", "ధాన్యం రవాణా"],
    dailyWage: 950,
    experience: "11 Years",
    rating: 4.9,
    reviewsCount: 31,
    status: "available",
    phone: "+91 93910 44556",
    whatsapp: "919391044556",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    verified: true,
    availableDates: ["2026-09-19", "2026-09-20", "2026-09-23"],
    equipment: ["Commercial Driving License", "Rotavator & Cultivator attachment knowledge"],
    bio_en: "Expert in deep ploughing, puddle making for paddy and heavy trailer transport across fields.",
    bio_te: "వరి దమ్ము కొట్టడం, లోతైన దుక్కి, రోటవేటర్ మరియు ట్రాలీ రవాణాలో 11 ఏళ్ల అనుభవం."
  },
  {
    id: "w5",
    name_en: "Nagaraju Labour Brigade",
    name_te: "నాగరాజు కూలీల బృందం",
    type: "group",
    groupSize: 18,
    district: "Guntur",
    mandal: "Bapatla",
    village: "Karlapalem",
    skills: ["harvesting", "loading", "planting"],
    skills_labels_en: ["Fast Harvesting", "Grain Bagging & Lifting", "Transplantation"],
    skills_labels_te: ["వరి & మొక్కజొన్న కోత", "బస్తాలు ఎత్తడం", "నాట్లు"],
    dailyWage: 600,
    experience: "14 Years",
    rating: 4.7,
    reviewsCount: 22,
    status: "available",
    phone: "+91 97011 22334",
    whatsapp: "919701122334",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80",
    verified: true,
    availableDates: ["2026-09-19", "2026-09-21", "2026-09-22"],
    equipment: ["Harvesting Tools", "Weighing balance support", "Vehicle available"],
    bio_en: "Large crew capable of completing 6+ acres per day. Has own auto-rickshaw for fast arrival.",
    bio_te: "18 మంది కూలీలతో కూడిన పెద్ద బృందం. స్వంత ఆటో సౌకర్యం కలదు, సమయానికి పొలానికి చేరుకుంటారు."
  },
  {
    id: "w6",
    name_en: "Malleswari & Gang",
    name_te: "మల్లేశ్వరి & బృందం",
    type: "group",
    groupSize: 8,
    district: "Warangal",
    mandal: "Narsampet",
    village: "Chennaraopet",
    skills: ["plucking", "weeding"],
    skills_labels_en: ["Cotton Plucking", "Chilli Harvesting", "Field Weeding"],
    skills_labels_te: ["పత్తి ఏరడం", "మిర్చి కోత", "కలుపు తీయడం"],
    dailyWage: 480,
    experience: "8 Years",
    rating: 4.8,
    reviewsCount: 19,
    status: "available",
    phone: "+91 91772 33445",
    whatsapp: "919177233445",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    verified: true,
    availableDates: ["2026-09-19", "2026-09-20", "2026-09-25"],
    equipment: ["Cotton sacks", "Clean plucking aprons"],
    bio_en: "Specialists in clean first-grade cotton plucking and dry chilli harvesting.",
    bio_te: "మొదటి గ్రేడ్ తెల్లటి పత్తి మరియు నాణ్యమైన మిర్చి ఏరడంలో ప్రత్యేక నైపుణ్యం."
  },
  {
    id: "w7",
    name_en: "Koteswara Rao",
    name_te: "కోటేశ్వరరావు (మల్టీ-స్కిల్డ్ వర్కర్)",
    type: "individual",
    groupSize: 1,
    district: "Krishna",
    mandal: "Gannavaram",
    village: "Kesarapalle",
    skills: ["spraying", "weeding", "harvesting"],
    skills_labels_en: ["Precision Spraying", "Manual Weeding", "Cutter Machine"],
    skills_labels_te: ["స్ప్రేయింగ్", "కలుపు తీత", "కట్టర్ మెషిన్"],
    dailyWage: 750,
    experience: "10 Years",
    rating: 4.9,
    reviewsCount: 16,
    status: "available",
    phone: "+91 99890 87654",
    whatsapp: "919989087654",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    verified: true,
    availableDates: ["2026-09-19", "2026-09-22", "2026-09-23"],
    equipment: ["Battery Sprayer", "Grass/Weed Cutter Machine"],
    bio_en: "Equipped with mechanical weed-cutter machine for orchard and paddy ridges.",
    bio_te: "గడ్డి కోసే మెషిన్ మరియు బ్యాటరీ స్ప్రేయర్‌తో తోటలు, గట్లకు ఉన్న కలుపును త్వరగా తొలగిస్తారు."
  },
  {
    id: "w8",
    name_en: "Bhavani Shankar Group",
    name_te: "భవాని శంకర్ శ్రామిక ముఠా",
    type: "group",
    groupSize: 12,
    district: "East Godavari",
    mandal: "Rajahmundry Rural",
    village: "Torredu",
    skills: ["planting", "harvesting", "loading"],
    skills_labels_en: ["Paddy Planting", "Combine Harvester Assistance", "Bag Loading"],
    skills_labels_te: ["వరి నాట్లు", "హార్వెస్టర్ మిషన్ సహాయం", "లోడింగ్"],
    dailyWage: 620,
    experience: "16 Years",
    rating: 5.0,
    reviewsCount: 52,
    status: "available",
    phone: "+91 98661 11223",
    whatsapp: "919866111223",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80",
    verified: true,
    availableDates: ["2026-09-19", "2026-09-20", "2026-09-21"],
    equipment: ["Transplantation rope markers", "Tarp covers"],
    bio_en: "Uniform distance SRI planting specialists and paddy bag loading directly onto lorries.",
    bio_te: "శ్రీ పద్ధతిలో క్రమ పద్ధతి నాట్లు మరియు లారీ లోడింగ్ పనులలో 16 ఏళ్ల సుదీర్ఘ అనుభవం."
  }
];

// Initial Job Openings by Farmers
const INITIAL_JOBS = [
  {
    id: "j1",
    farmerName: "Kondaveeti Sambasiva Rao (రైతు సాంబశివరావు)",
    phone: "+91 98485 55443",
    whatsapp: "919848555443",
    district: "Guntur",
    mandal: "Tenali",
    village: "Kolakaluru",
    crop: "Paddy (వరి)",
    workType: "harvesting",
    workTypeLabel_en: "Paddy Crop Harvesting & Bundling",
    workTypeLabel_te: "వరి పంట కోత మరియు కట్టలు కట్టడం",
    workersNeeded: 12,
    offeredWage: 700,
    workDate: "2026-09-20",
    duration: "2 Days (8 Acres)",
    foodProvided: true,
    description_en: "Urgent paddy harvest for 8 acres BPT 5204 crop. Need experienced group with sickles. Morning tea & afternoon lunch provided at farm.",
    description_te: "8 ఎకరాల BPT 5204 వరి కోతకు 12 మంది కూలీలు కావాలి. భోజనం మరియు టీ అందించబడును.",
    postedAgo: "2 hours ago"
  },
  {
    id: "j2",
    farmerName: "Gadde Anjaneyulu (రైతు ఆంజనేయులు)",
    phone: "+91 94412 88776",
    whatsapp: "919441288776",
    district: "Guntur",
    mandal: "Mangalagiri",
    village: "Nidamarru",
    crop: "Chilli (మిర్చి)",
    workType: "spraying",
    workTypeLabel_en: "Chilli Bio-Pesticide & Tonic Spraying",
    workTypeLabel_te: "మిర్చి తోటకు టానిక్ మరియు పురుగు మందు పిచికారీ",
    workersNeeded: 3,
    offeredWage: 850,
    workDate: "2026-09-19",
    duration: "1 Day (5 Acres)",
    foodProvided: true,
    description_en: "Need 3 sprayers with motor equipment for 5 acres Teja chilli farm. Water supply and drums ready at borewell.",
    description_te: "5 ఎకరాల తేజా మిర్చి తోటకు పవర్ స్ప్రేయర్‌లతో పిచికారీ చేయడానికి 3గురు స్ప్రేయర్లు కావాలి.",
    postedAgo: "30 mins ago"
  },
  {
    id: "j3",
    farmerName: "Chalasani Venkatesh (రైతు వెంకటేష్)",
    phone: "+91 98665 44332",
    whatsapp: "919866544332",
    district: "Krishna",
    mandal: "Gudivada",
    village: "Billapadu",
    crop: "Paddy (వరి)",
    workType: "planting",
    workTypeLabel_en: "Paddy Seedling Transplantation",
    workTypeLabel_te: "వరి నారు నాట్లు వేయడం",
    workersNeeded: 10,
    offeredWage: 550,
    workDate: "2026-09-21",
    duration: "1 Day (4 Acres)",
    foodProvided: true,
    description_en: "Field is ready with puddled mud. Need 10 women workers for speedy seedling plantation. Transport pick-up from Gudivada bypass.",
    description_te: "4 ఎకరాల పొలం దమ్ము చేసి సిద్ధంగా ఉంది. నాట్లు వేయడానికి 10 మంది మహిళా కూలీలు కావాలి. రవాణా సదుపాయం కలదు.",
    postedAgo: "4 hours ago"
  },
  {
    id: "j4",
    farmerName: "Mopidevi Suresh (రైతు సురేష్)",
    phone: "+91 97045 66778",
    whatsapp: "919704566778",
    district: "West Godavari",
    mandal: "Bhimavaram",
    village: "Dharmavaram",
    crop: "Fish Ponds & Paddy (చేపల చెరువు & వరి)",
    workType: "loading",
    workTypeLabel_en: "Feed Bag Loading & Paddy Shifting",
    workTypeLabel_te: "మేత బస్తాల లోడింగ్ & ధాన్యం రవాణా",
    workersNeeded: 6,
    offeredWage: 750,
    workDate: "2026-09-20",
    duration: "1 Day",
    foodProvided: false,
    description_en: "Loading 300 paddy & feed bags into Eicher truck. Fast payment on same evening in cash or UPI.",
    description_te: "300 బస్తాలు ఐషర్ లారీ లోకి లోడింగ్ చేయాలి. పని పూర్తికాగానే సాయంత్రం నగదు లేదా ఫోన్‌పే చెల్లింపు.",
    postedAgo: "5 hours ago"
  },
  {
    id: "j5",
    farmerName: "Bandi Tirupathi (రైతు తిరుపతి)",
    phone: "+91 91778 99887",
    whatsapp: "919177899887",
    district: "Warangal",
    mandal: "Parkal",
    village: "Nagaram",
    crop: "Cotton (పత్తి)",
    workType: "plucking",
    workTypeLabel_en: "Cotton First Picking (పత్తి ఏరడం)",
    workTypeLabel_te: "పత్తి మొదటి కోత / ఏరడం",
    workersNeeded: 8,
    offeredWage: 500,
    workDate: "2026-09-22",
    duration: "3 Days (6 Acres)",
    foodProvided: true,
    description_en: "White boll first plucking. Paying ₹12 per kg or fixed ₹500 daily wage + tea snack.",
    description_te: "మొదటి పత్తి ఏరడానికి 8 మంది కూలీలు కావాలి. కేజీకి ₹12 లేదా రోజుకు ₹500 కూలి.",
    postedAgo: "1 day ago"
  }
];

// Standard Agricultural Daily Wage Reference Rate Guide
const WAGE_BENCHMARK_DATA = [
  {
    operation_en: "Paddy Harvesting (వరి కోత)",
    operation_te: "వరి పంట కోత",
    crop_en: "Paddy / Rice",
    crop_te: "వరి",
    wageRange: "₹600 - ₹750",
    ratePerAcre: "₹3,500 - ₹4,500 / acre",
    hours: "7:00 AM - 2:00 PM (7 Hrs)",
    demand: "Peak Season"
  },
  {
    operation_en: "Paddy Transplantation / Planting (నాట్లు)",
    operation_te: "వరి నాట్లు వేయడం",
    crop_en: "Paddy",
    crop_te: "వరి",
    wageRange: "₹500 - ₹650",
    ratePerAcre: "₹3,200 - ₹3,800 / acre",
    hours: "8:00 AM - 3:00 PM (7 Hrs)",
    demand: "High Demand"
  },
  {
    operation_en: "Pesticide & Fertilizer Spraying (మందుల పిచికారీ)",
    operation_te: "మందుల పిచికారీ",
    crop_en: "Chilli, Cotton, Paddy, Vegetables",
    crop_te: "మిర్చి, పత్తి, వరి, కూరగాయలు",
    wageRange: "₹750 - ₹950",
    ratePerAcre: "₹180 - ₹250 / tank (drum)",
    hours: "6:30 AM - 11:30 AM (Cool Morning)",
    demand: "Consistent"
  },
  {
    operation_en: "Weeding & Ridge Cleaning (కలుపు తీత)",
    operation_te: "కలుపు తీత & గట్లు శుభ్రం",
    crop_en: "Cotton, Maize, Chilli, Pulses",
    crop_te: "పత్తి, మొక్కజొన్న, మిర్చి, అపరాలు",
    wageRange: "₹450 - ₹550",
    ratePerAcre: "₹2,200 - ₹2,800 / acre",
    hours: "8:00 AM - 4:00 PM (with lunch break)",
    demand: "Regular"
  },
  {
    operation_en: "Cotton & Chilli Plucking (పత్తి / మిర్చి ఏరడం)",
    operation_te: "పత్తి / మిర్చి ఏరడం",
    crop_en: "Cotton, Red Chilli",
    crop_te: "పత్తి, ఎర్ర మిరప",
    wageRange: "₹480 - ₹600",
    ratePerAcre: "₹10 - ₹14 per kg picked",
    hours: "8:00 AM - 4:00 PM",
    demand: "High Demand"
  },
  {
    operation_en: "Tractor & Heavy Machinery Operator (ట్రాక్టర్ నడపడం)",
    operation_te: "ట్రాక్టర్ & మిషన్ ఆపరేటర్",
    crop_en: "All Crop Fields",
    crop_te: "అన్ని పొలాలు",
    wageRange: "₹850 - ₹1,100",
    ratePerAcre: "₹1,200 - ₹1,600 / hr ploughing",
    hours: "Flexible 8 Hours",
    demand: "High Demand"
  },
  {
    operation_en: "Grain Bagging & Loading (ధాన్యం మోత & లోడింగ్)",
    operation_te: "ధాన్యం బస్తాలు మోత",
    crop_en: "Paddy, Maize, Cotton bales",
    crop_te: "వరి, మొక్కజొన్న, పత్తి బస్తాలు",
    wageRange: "₹700 - ₹900",
    ratePerAcre: "₹8 - ₹12 per 75kg bag",
    hours: "Flexible Task-based",
    demand: "Harvest Season"
  }
];

// Testimonials & Reviews
const INITIAL_REVIEWS = [
  {
    author: "K. Appa Rao (Farmer, Tenali)",
    author_te: "కె. అప్పారావు (రైతు, తెనాలి)",
    role: "Farmer (12 Acres Paddy)",
    rating: 5,
    date: "2 days ago",
    comment_en: "Saved my 6 acres harvest right before cyclone rain! Used the Emergency Labour feature at 7 AM and got a 14-member group by 9 AM. Exceptional service!",
    comment_te: "తుఫాను వర్షానికి ముందు నా 6 ఎకరాల వరి పంటను కాపాడారు! ఉదయం 7 గంటలకు ఎమర్జెన్సీ లేబర్ అడగ్గానే 9 గంటలకే 14 మంది ముఠా వచ్చింది. అద్భుతమైన సేవ!"
  },
  {
    author: "M. Rambabu (Gang Leader, Burripalem)",
    author_te: "ఎం. రాంబాబు (కూలీల మేస్త్రి, బుర్రిపాలెం)",
    role: "Labour Group Head (15 Members)",
    rating: 5,
    date: "1 week ago",
    comment_en: "Our gang used to sit without work on some days. Now with this website, farmers call us 3 days in advance and daily wages are settled without middleman cuts.",
    comment_te: "గతంలో మా ముఠాకు కొన్ని రోజులు పని ఉండేది కాదు. ఇప్పుడు రైతులు 3 రోజుల ముందే ఫోన్ చేసి బుక్ చేసుకుంటున్నారు. ఒక్క రూపాయి కమీషన్ లేకుండా పూర్తి కూలి అందుతోంది."
  },
  {
    author: "B. Nageswara Rao (Farmer, Mangalagiri)",
    author_te: "బి. నాగేశ్వరరావు (రైతు, మంగళగిరి)",
    role: "Chilli Farmer (4 Acres)",
    rating: 5,
    date: "2 weeks ago",
    comment_en: "Found a certified power sprayer within 15 minutes. Very transparent wage guide helped us agree on fair rates instantly.",
    comment_te: "15 నిమిషాల్లో మిర్చి స్ప్రేయర్‌ను కనుగొన్నాము. కూలి రేట్ల మార్గదర్శి వల్ల పారదర్శకంగా న్యాయమైన రేటుతో మాట్లాడుకున్నాము."
  }
];
